## RENT 데이터 가공

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import gmplot 
import statistics

from pandas import DataFrame

In [21]:
train_rent = pd.read_csv('./data/rent/total_rent.csv')
train_rent.head(7)
# len(train_rent)

,STATION,YEAR,MONTH,DAY,HOUR,WEEKDAY,SEASON,TEMPERATURE,RAINFALL,WINDSPEED,HUMLDITY,SNOWFALL,RENTCOUNT
0,1,2013,1,1,0,2,3,-8.8,NaN,0.1,90.0,8.8,0
1,1,2013,1,1,1,2,3,-8.5,NaN,0.9,90.0,8.8,0
2,1,2013,1,1,2,2,3,-8.5,NaN,1.0,89.0,8.8,0
3,1,2013,1,1,3,2,3,-9.0,NaN,0.7,91.0,8.8,0
4,1,2013,1,1,4,2,3,-9.1,NaN,0.6,92.0,8.8,0
5,1,2013,1,1,5,2,3,-9.4,NaN,0.5,92.0,8.8,0
6,1,2013,1,1,6,2,3,-9.0,NaN,1.4,93.0,8.8,0

In [22]:
tashu = pd.read_csv('./data/clean/tashu.csv')
# len(rent)
tashu.head(7)

,RENT_STATION,RENT_YEAR,RENT_MONTH,RENT_DAY,RENT_HOUR,RETURN_STATION,RETURN_YEAR,RETURN_MONTH,RETURN_DAY,RETURN_HOUR
0,43.0,2013,1,1,5,34.0,2013.0,1.0,1.0,6.0
1,97.0,2013,1,1,6,NaN,2013.0,1.0,1.0,10.0
2,2.0,2013,1,1,6,10.0,2013.0,1.0,1.0,6.0
3,106.0,2013,1,1,10,105.0,2013.0,1.0,1.0,10.0
4,4.0,2013,1,1,11,4.0,2013.0,1.0,1.0,12.0
5,21.0,2013,1,1,11,105.0,2013.0,1.0,1.0,11.0
6,90.0,2013,1,1,12,91.0,2013.0,1.0,1.0,12.0

In [23]:
rent_clean = train_rent.drop(columns=['WEEKDAY', 'SEASON', 'TEMPERATURE','RAINFALL',
                                      'WINDSPEED','HUMLDITY','SNOWFALL'])

rent = tashu.rename(columns = {'RENT_STATION': 'STATION', 'RENT_YEAR': 'YEAR', 
                                        'RENT_MONTH': 'MONTH', 'RENT_DAY': 'DAY', 'RENT_HOUR': 'HOUR'})

In [25]:
rent_join = pd.merge(rent_clean, rent, how='outer')

In [7]:
rent_join = rent_join.dropna()

In [8]:
rent_join

,STATION,YEAR,MONTH,DAY,HOUR,RENTCOUNT,RETURN_STATION,RETURN_YEAR,RETURN_MONTH,RETURN_DAY,RETURN_HOUR
13,1.0,2013,1,1,13,0.0,1.0,2013.0,1.0,1.0,13.0
14,1.0,2013,1,1,13,0.0,2.0,2013.0,1.0,1.0,15.0
15,1.0,2013,1,1,13,0.0,2.0,2013.0,1.0,1.0,15.0
33,1.0,2013,1,2,7,0.0,1.0,2013.0,1.0,2.0,7.0
34,1.0,2013,1,2,7,0.0,12.0,2013.0,1.0,2.0,8.0
38,1.0,2013,1,2,11,0.0,10.0,2013.0,1.0,2.0,11.0
45,1.0,2013,1,2,18,0.0,29.0,2013.0,1.0,2.0,18.0
62,1.0,2013,1,3,11,0.0,29.0,2013.0,1.0,3.0,12.0
93,1.0,2013,1,4,18,0.0,13.0,2013.0,1.0,4.0,18.0
106,1.0,2013,1,5,7,0.0,45.0,2013.0,1.0,8.0,18.0
113,1.0,2013,1,5,14,0.0,1.0,2013.0,1.0,5.0,14.0
114,1.0,2013,1,5,15,0.0,1.0,2013.0,1.0,5.0,15.0
115,1.0,2013,1,5,15,0.0,8.0,2013.0,1.0,5.0,16.0
138,1.0,2013,1,6,14,0.0,8.0,2013.0,1.0,6.0,15.0
144,1.0,2013,1,6,20,0.0,31.0,2013.0,1.0,6.0,20.0
145,1.0,2013,1,6,20,0.0,31.0,2013.0,1.0,6.0,20.0
156,1.0,2013,1,7,7,0.0,12.0,2013.0,1.0,7.0,8.0
162,1.0,2013,1,7,13,0.0,27.0,2013.0,1.0,7.0,13.0
168,1.0,2013,1,7,19,0.0,4.0,2013.0,1.0,7.0,19.0
184,1.0,2013,1,8,11,0.0,29.0,2013.0,1.0,8.0,12.0
187,1.0,2013,1,8,14,0.0,2.0,2013.0,1.0,8.0,15.0
188,1.0,2013,1,8,15,0.0,1.0,2013.0,1.0,8.0,15.0
190,1.0,2013,1,8,17,0.0,17.0,2013.0,1.0,8.0,18.0
191,1.0,2013,1,8,17,0.0,17.0,2013.0,1.0,8.0,18.0
192,1.0,2013,1,8,17,0.0,17.0,2013.0,1.0,8.0,18.0
193,1.0,2013,1,8,17,0.0,14.0,2013.0,1.0,8.0,17.0
195,1.0,2013,1,8,19,0.0,1.0,2013.0,1.0,8.0,19.0
196,1.0,2013,1,8,19,0.0,1.0,2013.0,1.0,8.0,19.0
197,1.0,2013,1,8,19,0.0,1.0,2013.0,1.0,8.0,19.0
198,1.0,2013,1,8,19,0.0,13.0,2013.0,1.0,8.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...
5955702,144.0,2015,12,29,15,0.0,31.0,2015.0,12.0,29.0,16.0
5955703,144.0,2015,12,29,15,0.0,144.0,2015.0,12.0,29.0,15.0
5955704,144.0,2015,12,29,15,0.0,188.0,2015.0,12.0,30.0,16.0
5955705,144.0,2015,12,29,15,0.0,57.0,2015.0,12.0,29.0,16.0
5955706,144.0,2015,12,29,16,0.0,31.0,2015.0,12.0,29.0,16.0
5955707,144.0,2015,12,29,17,0.0,57.0,2015.0,12.0,29.0,17.0
5955708,144.0,2015,12,29,17,0.0,31.0,2015.0,12.0,29.0,17.0
5955709,144.0,2015,12,29,17,0.0,57.0,2015.0,12.0,29.0,17.0
5955710,144.0,2015,12,29,17,0.0,31.0,2015.0,12.0,29.0,17.0
5955723,144.0,2015,12,30,6,0.0,144.0,2015.0,12.0,30.0,6.0
5955724,144.0,2015,12,30,6,0.0,144.0,2015.0,12.0,30.0,6.0
5955739,144.0,2015,12,30,21,0.0,144.0,2015.0,12.0,30.0,21.0
5955749,144.0,2015,12,31,7,0.0,144.0,2015.0,12.0,31.0,7.0
5955750,144.0,2015,12,31,7,0.0,144.0,2015.0,12.0,31.0,7.0
5955751,144.0,2015,12,31,7,0.0,144.0,2015.0,12.0,31.0,7.0
5955758,144.0,2015,12,31,14,0.0,144.0,2015.0,12.0,31.0,16.0
5955760,144.0,2015,12,31,16,0.0,144.0,2015.0,12.0,31.0,16.0
5955761,144.0,2015,12,31,16,0.0,31.0,2015.0,12.0,31.0,16.0
5955762,144.0,2015,12,31,16,0.0,31.0,2015.0,12.0,31.0,17.0
5955763,144.0,2015,12,31,16,0.0,31.0,2015.0,12.0,31.0,17.0
5955764,144.0,2015,12,31,17,0.0,31.0,2015.0,12.0,31.0,17.0
5955765,144.0,2015,12,31,17,0.0,31.0,2015.0,12.0,31.0,17.0
5955766,144.0,2015,12,31,17,0.0,31.0,2015.0,12.0,31.0,17.0
5955767,144.0,2015,12,31,17,0.0,31.0,2015.0,12.0,31.0,17.0
5955768,144.0,2015,12,31,17,0.0,31.0,2015.0,12.0,31.0,17.0
5955771,144.0,2015,12,31,20,0.0,31.0,2015.0,12.0,31.0,20.0
5955772,144.0,2015,12,31,20,0.0,31.0,2015.0,12.0,31.0,20.0
5955774,144.0,2015,12,31,22,0.0,21.0,2015.0,12.0,31.0,23.0
5955775,144.0,2015,12,31,22,0.0,21.0,2015.0,12.0,31.0,23.0
5955776,144.0,2015,12,31,22,0.0,23.0,2015.0,12.0,31.0,22.0

In [9]:
temp = rent_join.groupby(['STATION','YEAR','MONTH','DAY','HOUR']).size().to_frame('RENTCOUNT').reset_index()

         STATION  YEAR  MONTH  DAY  HOUR  RENTCOUNT
0            1.0  2013      1    1    13          3
1            1.0  2013      1    2     7          2
2            1.0  2013      1    2    11          1
3            1.0  2013      1    2    18          1
4            1.0  2013      1    3    11          1
5            1.0  2013      1    4    18          1
6            1.0  2013      1    5     7          1
7            1.0  2013      1    5    14          1
8            1.0  2013      1    5    15          2
9            1.0  2013      1    6    14          1
10           1.0  2013      1    6    20          2
11           1.0  2013      1    7     7          1
12           1.0  2013      1    7    13          1
13           1.0  2013      1    7    19          1
14           1.0  2013      1    8    11          1
15           1.0  2013      1    8    14          1
16           1.0  2013      1    8    15          1
17           1.0  2013      1    8    17          4
18           1.0  2013      1    8    19          4
19           1.0  2013      1    9     9          1
20           1.0  2013      1    9    15          3
21           1.0  2013      1    9    22          1
22           1.0  2013      1   10     8          1
23           1.0  2013      1   10    17          1
24           1.0  2013      1   10    19          1
25           1.0  2013      1   11    18          1
26           1.0  2013      1   12     9          1
27           1.0  2013      1   12    12          2
28           1.0  2013      1   13    13          1
29           1.0  2013      1   13    16          1
...          ...   ...    ...  ...   ...        ...
1132126    144.0  2015     12   23    16          2
1132127    144.0  2015     12   24     7          2
1132128    144.0  2015     12   24    22          2
1132129    144.0  2015     12   25     6          2
1132130    144.0  2015     12   25    14          1
1132131    144.0  2015     12   25    15          2
1132132    144.0  2015     12   25    16          1
1132133    144.0  2015     12   25    17          1
1132134    144.0  2015     12   26     6          2
1132135    144.0  2015     12   26    16         14
1132136    144.0  2015     12   26    17          1
1132137    144.0  2015     12   26    18          1
1132138    144.0  2015     12   27     6          3
1132139    144.0  2015     12   27    13          1
1132140    144.0  2015     12   27    15          1
1132141    144.0  2015     12   28     6          2
1132142    144.0  2015     12   29    11          2
1132143    144.0  2015     12   29    12          2
1132144    144.0  2015     12   29    14          2
1132145    144.0  2015     12   29    15          6
1132146    144.0  2015     12   29    16          1
1132147    144.0  2015     12   29    17          4
1132148    144.0  2015     12   30     6          2
1132149    144.0  2015     12   30    21          1
1132150    144.0  2015     12   31     7          3
1132151    144.0  2015     12   31    14          1
1132152    144.0  2015     12   31    16          4
1132153    144.0  2015     12   31    17          5
1132154    144.0  2015     12   31    20          2
1132155    144.0  2015     12   31    22          3

[1132156 rows x 6 columns]

In [10]:
train_rent = train_rent.drop(columns=['RENTCOUNT'])

In [11]:
train_rent = pd.merge(train_rent, temp, how='outer')

In [16]:
train_rent = train_rent.replace({'RENTCOUNT': np.nan}, {'RENTCOUNT': 0.0})

In [17]:
train_rent

,STATION,YEAR,MONTH,DAY,HOUR,WEEKDAY,SEASON,TEMPERATURE,RAINFALL,WINDSPEED,HUMLDITY,SNOWFALL,RENTCOUNT
0,1,2013,1,1,0,2,3,-8.8,NaN,0.1,90.0,8.8,0.0
1,1,2013,1,1,1,2,3,-8.5,NaN,0.9,90.0,8.8,0.0
2,1,2013,1,1,2,2,3,-8.5,NaN,1.0,89.0,8.8,0.0
3,1,2013,1,1,3,2,3,-9.0,NaN,0.7,91.0,8.8,0.0
4,1,2013,1,1,4,2,3,-9.1,NaN,0.6,92.0,8.8,0.0
5,1,2013,1,1,5,2,3,-9.4,NaN,0.5,92.0,8.8,0.0
6,1,2013,1,1,6,2,3,-9.0,NaN,1.4,93.0,8.8,0.0
7,1,2013,1,1,7,2,3,-8.3,NaN,0.2,94.0,9.6,0.0
8,1,2013,1,1,8,2,3,-7.3,NaN,1.7,96.0,10.5,0.0
9,1,2013,1,1,9,2,3,-6.4,2.2,0.9,96.0,12.8,0.0
10,1,2013,1,1,10,2,3,-5.3,NaN,0.4,98.0,15.3,0.0
11,1,2013,1,1,11,2,3,-3.4,NaN,0.9,93.0,15.5,0.0
12,1,2013,1,1,12,2,3,-0.5,1.9,0.7,88.0,15.0,0.0
13,1,2013,1,1,13,2,3,3.1,NaN,2.0,73.0,14.0,3.0
14,1,2013,1,1,14,2,3,2.5,NaN,2.4,69.0,12.5,0.0
15,1,2013,1,1,15,2,3,0.8,0.2,3.8,90.0,12.5,0.0
16,1,2013,1,1,16,2,3,1.1,NaN,2.4,84.0,13.8,0.0
17,1,2013,1,1,17,2,3,0.5,NaN,2.2,83.0,14.0,0.0
18,1,2013,1,1,18,2,3,-1.4,0.5,0.5,90.0,14.0,0.0
19,1,2013,1,1,19,2,3,-1.7,NaN,1.2,94.0,14.0,0.0
20,1,2013,1,1,20,2,3,-2.0,NaN,1.0,95.0,14.0,0.0
21,1,2013,1,1,21,2,3,-2.4,NaN,1.1,98.0,14.0,0.0
22,1,2013,1,1,22,2,3,-3.3,NaN,0.2,97.0,14.0,0.0
23,1,2013,1,1,23,2,3,-3.2,NaN,1.4,98.0,14.1,0.0
24,1,2013,1,2,0,3,3,-1.3,0.8,2.5,100.0,15.7,0.0
25,1,2013,1,2,1,3,3,-0.8,NaN,0.9,100.0,18.1,0.0
26,1,2013,1,2,2,3,3,-1.3,NaN,3.4,89.0,18.3,0.0
27,1,2013,1,2,3,3,3,-3.5,1.8,3.8,80.0,18.3,0.0
28,1,2013,1,2,4,3,3,-5.3,NaN,2.8,79.0,18.4,0.0
29,1,2013,1,2,5,3,3,-6.5,NaN,1.8,83.0,18.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3784290,144,2015,12,30,18,3,3,4.2,NaN,1.3,67.0,NaN,0.0
3784291,144,2015,12,30,19,3,3,4.3,NaN,1.1,66.0,NaN,0.0
3784292,144,2015,12,30,20,3,3,3.3,NaN,2.5,87.0,NaN,0.0
3784293,144,2015,12,30,21,3,3,2.7,1.0,2.8,92.0,NaN,1.0
3784294,144,2015,12,30,22,3,3,2.0,NaN,2.1,94.0,NaN,0.0
3784295,144,2015,12,30,23,3,3,1.8,NaN,1.4,95.0,NaN,0.0
3784296,144,2015,12,31,0,4,3,1.8,0.6,1.5,94.0,NaN,0.0
3784297,144,2015,12,31,1,4,3,1.7,NaN,0.5,94.0,NaN,0.0
3784298,144,2015,12,31,2,4,3,1.3,NaN,0.6,96.0,NaN,0.0
3784299,144,2015,12,31,3,4,3,1.0,NaN,1.0,96.0,NaN,0.0
3784300,144,2015,12,31,4,4,3,1.0,NaN,0.9,97.0,NaN,0.0
3784301,144,2015,12,31,5,4,3,0.4,NaN,0.5,97.0,NaN,0.0
3784302,144,2015,12,31,6,4,3,0.4,NaN,0.5,97.0,NaN,0.0
3784303,144,2015,12,31,7,4,3,0.0,NaN,1.2,97.0,NaN,3.0
3784304,144,2015,12,31,8,4,3,0.0,NaN,1.4,97.0,NaN,0.0
3784305,144,2015,12,31,9,4,3,0.4,NaN,0.3,97.0,NaN,0.0
3784306,144,2015,12,31,10,4,3,1.5,NaN,0.8,97.0,NaN,0.0
3784307,144,2015,12,31,11,4,3,2.4,NaN,1.2,90.0,NaN,0.0
3784308,144,2015,12,31,12,4,3,3.8,NaN,2.6,70.0,NaN,0.0
3784309,144,2015,12,31,13,4,3,4.7,NaN,2.1,65.0,NaN,0.0
3784310,144,2015,12,31,14,4,3,5.4,NaN,2.2,59.0,NaN,1.0
3784311,144,2015,12,31,15,4,3,5.5,NaN,1.8,57.0,NaN,0.0
3784312,144,2015,12,31,16,4,3,4.9,NaN,1.8,59.0,NaN,4.0
3784313,144,2015,12,31,17,4,3,4.2,NaN,1.1,62.0,NaN,5.0
3784314,144,2015,12,31,18,4,3,2.7,NaN,1.2,68.0,NaN,0.0
3784315,144,2015,12,31,19,4,3,1.2,NaN,1.0,76.0,NaN,0.0
3784316,144,2015,12,31,20,4,3,0.4,NaN,0.8,80.0,NaN,2.0
3784317,144,2015,12,31,21,4,3,0.0,NaN,0.5,83.0,NaN,0.0
3784318,144,2015,12,31,22,4,3,-1.0,NaN,1.1,87.0,NaN,3.0
3784319,144,2015,12,31,23,4,3,-1.4,NaN,0.2,90.0,NaN,0.0

In [18]:
train_rent.to_csv('total_rent.csv',index=False)